#!/bin/sh

#PBS -lselect=1:ncpus=48:mem=16gb
#PBS -lwalltime=08:00:00
#PBS -o /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files


export OMP_NUM_THREADS=48

echo Using 48 cores
echo Using 16GB of RAM
echo Walltime: 8 hours

echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/run_file.sh
sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/run_file.sh




