#!/bin/sh
#PBS -lselect=1:ncpus=64:mem=32gb
#PBS -lwalltime=01:00:00
#PBS -o /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=64

echo Using 64 cores
echo Using 32GB of RAM

echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_for_plot_BH_lambdas.sh
sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_for_plot_BH_lambdas.sh
