#!/bin/sh
#PBS -lselect=1:ncpus=48:mem=16gb
#PBS -lwalltime=02:00:00
#PBS -o /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=48

echo Using 48 cores
echo Using 16GB of RAM

echo Running /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_HRVcounting_mass_1.0_N_multiplier_10000_N_reps_50.sh
sh /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_HRVcounting_mass_1.0_N_multiplier_10000_N_reps_50.sh
