#!/bin/sh
#PBS -lselect=1:ncpus=256:mem=3000gb
#PBS -lwalltime=24:00:00
#PBS -o /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=256

echo Using 256 cores
echo Using 3000GB of RAM

echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_lambdacounting_mass_3.0239_Rho5000_N_reps_30_Nth7.sh
sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_lambdacounting_mass_3.0239_Rho5000_N_reps_30_Nth7.sh
