#!/bin/sh
#PBS -lselect=1:ncpus=256:mem=920gb
#PBS -lwalltime=4:00:00
#PBS -o /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=256

echo Using 256 cores
echo Using 920GB of RAM

echo Running /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_lambdacounting_mass_1.4_N_multiplier__N_reps_25.sh
sh /rds/general/user/sv519/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_lambdacounting_mass_1.4_N_multiplier__N_reps_25.sh
