#!/bin/sh
#PBS -lselect=1:ncpus=256:mem=920gb
#PBS -lwalltime=08:00:00
#PBS -o /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=256

echo Using 256 cores
echo Using 920GB of RAM

echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_3.1_N_multiplier_20000_N_reps_50.sh
sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_3.1_N_multiplier_20000_N_reps_50.sh
