#!/bin/sh
#PBS -lselect=1:ncpus=48:mem=16gb
#PBS -lwalltime=00:30:00
#PBS -o /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=48

echo Using 48 cores
echo Using 16GB of RAM

sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_1.5_N_multiplier_400_N_reps_10.sh
echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_1.5_N_multiplier_400_N_reps_10.sh
