#!/bin/sh
#PBS -lselect=1:ncpus=48:mem=16gb
#PBS -lwalltime=01:00:00
#PBS -o /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/out_files
#PBS -e /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/err_files

export OMP_NUM_THREADS=48

echo Using 48 cores
echo Using 16GB of RAM

echo Running /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_2.8_N_multiplier_1000_N_reps_100.sh
sh /rds/general/user/vh119/home/MSci_Schwarzschild_Causets/job_submission/submitted_jobs/runfile_files/run_file_linkcounting_mass_2.8_N_multiplier_1000_N_reps_100.sh
